name: Handle Automation Requests

on:
  issues:
    types: [opened]
    labels: 
      - automation-request

jobs:
  notify-team:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification email
      uses: atlassian/gajira-cli@master
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: New Ansible Automation Request
        body: |
          A new automation request has been submitted:
          - **Title**: ${{ github.event.issue.title }}
          - **Link**: ${{ github.event.issue.html_url }}
        to: ncsu.ee2017@gmail.com
        from: GitHub Actions <noreply@example.com>
