name: Handle Automation Requests

on:
  issues:
    types: [opened]
    labels: 
      - automation-request

jobs:
  notify-team:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification email
      uses: atlassian/gajira-cli@master
      env:
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
      run: |
        curl -H 'Content-Type: application/json' -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "0076D7",
          "summary": "New Ansible Automation Request",
          "sections": [{
            "activityTitle": "New Ansible Automation Request",
            "activitySubtitle": "GitHub Issue Notification",
            "facts": [{
              "name": "Title:",
              "value": "${{ github.event.issue.title }}"
            }, {
              "name": "Link:",
              "value": "<a href=\"${{ github.event.issue.html_url }}\">View on GitHub</a>"
            }],
            "markdown": true
          }]
        }' $TEAMS_WEBHOOK_URL